name: dbt_scooters_finance
version: "1.0.0"

profile: dbt_scooters_finance

model-paths: [models]
test-paths: [tests]
macro-paths: [macros]

clean-targets:
  - target

models:
  dbt_scooters_finance:
    +materialized: table
