name: Deploy dbt docs (Data Catalog) to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install requirements of dbt project
        run: pip install -r requirements.txt

      - name: Install DuckDB for additional tasks
        uses: opt-nc/setup-duckdb-action@v1.0.8

      - name: Build project for validation
        run: |
          dbt build
          chmod +x post_commands.sh && ./post_commands.sh

      - name: Generate docs
        run: dbt docs generate

      - name: Prepare site files
        run: |
          mkdir site
          cp target/index.html site/
          cp target/manifest.json site/
          cp target/catalog.json site/

      - name: Commit site for GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
