version: 2

sources:
  - name: s3
    meta:
      external_location: "s3://inzhenerka-public/scooters_data_generator/{name}.parquet"
    tables:
      - name: trips

  - name: finance_data
    meta:
      external_location: "finance_data/{name}.csv"
    tables:
      - name: rates

models:

  - name: all_costs
    description: ""
    config:
      materialized: 'external'
      location: 'output_data/all_costs.csv'

  - name: profit
    description: ""
    config:
      materialized: 'external'
      location: 'output_data/profit.csv'
